#!/bin/bash

rm -rf "/Library/PreferenceBundles/unlocksound7prefs.bundle/zh_TW.lproj/unlocksound7prefs.strings"

echo " 中文字體包已經移除了！"

declare -a cydia
if [[ ${CYDIA+@} ]]; then
	eval "echo 'finish:killall SpringBoard' >&${cydia[0]}"
fi
exit 0
